// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

/**
 * GetDataDir 返回数据目录（供前端调用）
 */
export function GetDataDir(): $CancellablePromise<string> {
    return $Call.ByID(2677410815);
}

/**
 * GetVersion 返回版本号
 */
export function GetVersion(): $CancellablePromise<string> {
    return $Call.ByID(3741982956);
}

/**
 * Ping 连通性测试
 */
export function Ping(): $CancellablePromise<string> {
    return $Call.ByID(2559294044);
}

export function SetApplication(wailsApp: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(151671058, wailsApp);
}
