// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * FindPerformers 分页查询演员列表。
 */
export function FindPerformers(input: $models.PerformersQuery): $CancellablePromise<$models.PerformersPageDTO | null> {
    return $Call.ByID(2212267212, input).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * FindScenes 分页查询场景列表，返回分页结果与总数。
 */
export function FindScenes(input: $models.ScenesQuery): $CancellablePromise<$models.ScenesPageDTO | null> {
    return $Call.ByID(3579858290, input).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * FindStudios 分页查询工作室列表。
 */
export function FindStudios(input: $models.StudiosQuery): $CancellablePromise<$models.StudiosPageDTO | null> {
    return $Call.ByID(2077282170, input).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * FindTags 分页查询标签列表。
 */
export function FindTags(input: $models.TagsQuery): $CancellablePromise<$models.TagsPageDTO | null> {
    return $Call.ByID(3917363242, input).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * GetDataDir 返回数据目录（供前端调用）
 */
export function GetDataDir(): $CancellablePromise<string> {
    return $Call.ByID(2677410815);
}

/**
 * GetScene returns the full detail DTO for a single scene.
 */
export function GetScene(id: number): $CancellablePromise<$models.SceneDetailDTO | null> {
    return $Call.ByID(3442445960, id).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * GetSystemStatus 简单状态查询（验证 Manager 是否活着）
 */
export function GetSystemStatus(): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(2642847171).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * GetVersion 返回版本号
 */
export function GetVersion(): $CancellablePromise<string> {
    return $Call.ByID(3741982956);
}

/**
 * Ping 连通性测试
 */
export function Ping(): $CancellablePromise<string> {
    return $Call.ByID(2559294044);
}

/**
 * ScanLibrary 触发扫描指定文件夹。返回 Job ID，前端可通过事件监听进度。
 */
export function ScanLibrary(path: string): $CancellablePromise<number> {
    return $Call.ByID(1786151488, path);
}

export function SetApplication(wailsApp: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(151671058, wailsApp);
}

// Private type creation functions
const $$createType0 = $models.PerformersPageDTO.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.ScenesPageDTO.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.StudiosPageDTO.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $models.TagsPageDTO.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $models.SceneDetailDTO.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = $Create.Map($Create.Any, $Create.Any);
