// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface SceneDTO {
    "id": number;
    "title": string;
    "path": string;
    "oshash": string;
    "checksum": string;
    "organized": boolean;
    "createdAt": string;
    "updatedAt": string;
}
