// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AttachmentDTO 是详情页的附件项。
 */
export interface AttachmentDTO {
    "name": string;
    "url": string;
    "width": number;
    "height": number;
}

/**
 * PerformerDTO pairs a performer ID with its name.
 */
export interface PerformerDTO {
    "id": number;
    "name": string;
}

export interface PerformersPageDTO {
    "performers": PerformerDTO[] | null;
    "total": number;
    "page": number;
    "pageSize": number;
}

export interface SceneDTO {
    "id": number;
    "title": string;
    "path": string;
    "oshash": string;
    "checksum": string;
    "organized": boolean;
    "tags": TagDTO[] | null;
    "performers": PerformerDTO[] | null;
    "createdAt": string;
    "updatedAt": string;
}

/**
 * SceneDetailDTO is the full representation returned by GetScene.
 */
export interface SceneDetailDTO {
    "id": number;
    "title": string;
    "code": string;
    "details": string;
    "director": string;
    "date": string;
    "productionDate": string;

    /**
     * Rating is expressed on a 1-100 scale; 0 means no rating.
     */
    "rating": number;
    "organized": boolean;
    "studioId": number | null;
    "studioName": string;
    "urls": string[] | null;
    "tags": TagDTO[] | null;
    "performers": PerformerDTO[] | null;

    /**
     * Cover fields. CoverURL is empty when no cover is available.
     */
    "coverUrl": string;
    "coverWidth": number;
    "coverHeight": number;

    /**
     * Attachments are filesystem-only extra images (fanart/poster/extra).
     */
    "attachments": AttachmentDTO[] | null;

    /**
     * Convenience fields for the primary file. Duration/FrameRate are 0 when
     * unknown; Resolution is empty when dimensions are unknown.
     */
    "path": string;
    "oshash": string;
    "checksum": string;
    "duration": number;
    "width": number;
    "height": number;
    "resolution": string;
    "videoCodec": string;
    "audioCodec": string;
    "frameRate": number;
    "bitrate": number;
    "files": SceneFileDTO[] | null;
    "createdAt": string;
    "updatedAt": string;
}

/**
 * SceneFileDTO is a single video file of a scene.
 */
export interface SceneFileDTO {
    "id": number;
    "path": string;
    "basename": string;
    "duration": number;
    "width": number;
    "height": number;
    "videoCodec": string;
    "audioCodec": string;
    "frameRate": number;
    "bitrate": number;
    "format": string;
}

/**
 * ScenesPageDTO 是场景列表的分页结果。
 */
export interface ScenesPageDTO {
    "scenes": SceneDTO[] | null;
    "total": number;
    "page": number;
    "pageSize": number;
}

/**
 * StudioDTO 是工作室的列表项。
 */
export interface StudioDTO {
    "id": number;
    "name": string;
}

export interface StudiosPageDTO {
    "studios": StudioDTO[] | null;
    "total": number;
    "page": number;
    "pageSize": number;
}

/**
 * TagDTO pairs a tag ID with its name so the frontend can look up either
 * without relying on parallel arrays.
 */
export interface TagDTO {
    "id": number;
    "name": string;
}

export interface TagsPageDTO {
    "tags": TagDTO[] | null;
    "total": number;
    "page": number;
    "pageSize": number;
}
