// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AttachmentDTO 是详情页的附件项。
 */
export class AttachmentDTO {
    "name": string;
    "url": string;
    "width": number;
    "height": number;

    /** Creates a new AttachmentDTO instance. */
    constructor($$source: Partial<AttachmentDTO> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("width" in $$source)) {
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            this["height"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AttachmentDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): AttachmentDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AttachmentDTO($$parsedSource as Partial<AttachmentDTO>);
    }
}

/**
 * PerformerDTO pairs a performer ID with its name.
 */
export class PerformerDTO {
    "id": number;
    "name": string;

    /** Creates a new PerformerDTO instance. */
    constructor($$source: Partial<PerformerDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PerformerDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): PerformerDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PerformerDTO($$parsedSource as Partial<PerformerDTO>);
    }
}

export class PerformersPageDTO {
    "performers": PerformerDTO[];
    "total": number;
    "page": number;
    "pageSize": number;

    /** Creates a new PerformersPageDTO instance. */
    constructor($$source: Partial<PerformersPageDTO> = {}) {
        if (!("performers" in $$source)) {
            this["performers"] = [];
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("page" in $$source)) {
            this["page"] = 0;
        }
        if (!("pageSize" in $$source)) {
            this["pageSize"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PerformersPageDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): PerformersPageDTO {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("performers" in $$parsedSource) {
            $$parsedSource["performers"] = $$createField0_0($$parsedSource["performers"]);
        }
        return new PerformersPageDTO($$parsedSource as Partial<PerformersPageDTO>);
    }
}

export class PerformersQuery {
    "query": string;
    "page": number;
    "pageSize": number;

    /** Creates a new PerformersQuery instance. */
    constructor($$source: Partial<PerformersQuery> = {}) {
        if (!("query" in $$source)) {
            this["query"] = "";
        }
        if (!("page" in $$source)) {
            this["page"] = 0;
        }
        if (!("pageSize" in $$source)) {
            this["pageSize"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PerformersQuery instance from a string or object.
     */
    static createFrom($$source: any = {}): PerformersQuery {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PerformersQuery($$parsedSource as Partial<PerformersQuery>);
    }
}

export class SceneDTO {
    "id": number;
    "title": string;
    "path": string;
    "oshash": string;
    "checksum": string;
    "organized": boolean;
    "tags": TagDTO[];
    "performers": PerformerDTO[];
    "createdAt": string;
    "updatedAt": string;

    /** Creates a new SceneDTO instance. */
    constructor($$source: Partial<SceneDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("oshash" in $$source)) {
            this["oshash"] = "";
        }
        if (!("checksum" in $$source)) {
            this["checksum"] = "";
        }
        if (!("organized" in $$source)) {
            this["organized"] = false;
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }
        if (!("performers" in $$source)) {
            this["performers"] = [];
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SceneDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): SceneDTO {
        const $$createField6_0 = $$createType3;
        const $$createField7_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField6_0($$parsedSource["tags"]);
        }
        if ("performers" in $$parsedSource) {
            $$parsedSource["performers"] = $$createField7_0($$parsedSource["performers"]);
        }
        return new SceneDTO($$parsedSource as Partial<SceneDTO>);
    }
}

/**
 * SceneDetailDTO is the full representation returned by GetScene.
 */
export class SceneDetailDTO {
    "id": number;
    "title": string;
    "code": string;
    "details": string;
    "director": string;
    "date": string;
    "productionDate": string;

    /**
     * Rating is expressed on a 1-100 scale; 0 means no rating.
     */
    "rating": number;
    "organized": boolean;
    "studioId": number | null;
    "studioName": string;
    "urls": string[];
    "tags": TagDTO[];
    "performers": PerformerDTO[];

    /**
     * Cover fields. CoverURL is empty when no cover is available.
     */
    "coverUrl": string;
    "coverWidth": number;
    "coverHeight": number;

    /**
     * Attachments are filesystem-only extra images (fanart/poster/extra).
     */
    "attachments": AttachmentDTO[];

    /**
     * Convenience fields for the primary file. Duration/FrameRate are 0 when
     * unknown; Resolution is empty when dimensions are unknown.
     */
    "path": string;
    "oshash": string;
    "checksum": string;
    "duration": number;
    "width": number;
    "height": number;
    "resolution": string;
    "videoCodec": string;
    "audioCodec": string;
    "frameRate": number;
    "bitrate": number;
    "files": SceneFileDTO[];
    "createdAt": string;
    "updatedAt": string;

    /** Creates a new SceneDetailDTO instance. */
    constructor($$source: Partial<SceneDetailDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("code" in $$source)) {
            this["code"] = "";
        }
        if (!("details" in $$source)) {
            this["details"] = "";
        }
        if (!("director" in $$source)) {
            this["director"] = "";
        }
        if (!("date" in $$source)) {
            this["date"] = "";
        }
        if (!("productionDate" in $$source)) {
            this["productionDate"] = "";
        }
        if (!("rating" in $$source)) {
            this["rating"] = 0;
        }
        if (!("organized" in $$source)) {
            this["organized"] = false;
        }
        if (!("studioId" in $$source)) {
            this["studioId"] = null;
        }
        if (!("studioName" in $$source)) {
            this["studioName"] = "";
        }
        if (!("urls" in $$source)) {
            this["urls"] = [];
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }
        if (!("performers" in $$source)) {
            this["performers"] = [];
        }
        if (!("coverUrl" in $$source)) {
            this["coverUrl"] = "";
        }
        if (!("coverWidth" in $$source)) {
            this["coverWidth"] = 0;
        }
        if (!("coverHeight" in $$source)) {
            this["coverHeight"] = 0;
        }
        if (!("attachments" in $$source)) {
            this["attachments"] = [];
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("oshash" in $$source)) {
            this["oshash"] = "";
        }
        if (!("checksum" in $$source)) {
            this["checksum"] = "";
        }
        if (!("duration" in $$source)) {
            this["duration"] = 0;
        }
        if (!("width" in $$source)) {
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            this["height"] = 0;
        }
        if (!("resolution" in $$source)) {
            this["resolution"] = "";
        }
        if (!("videoCodec" in $$source)) {
            this["videoCodec"] = "";
        }
        if (!("audioCodec" in $$source)) {
            this["audioCodec"] = "";
        }
        if (!("frameRate" in $$source)) {
            this["frameRate"] = 0;
        }
        if (!("bitrate" in $$source)) {
            this["bitrate"] = 0;
        }
        if (!("files" in $$source)) {
            this["files"] = [];
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SceneDetailDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): SceneDetailDTO {
        const $$createField11_0 = $$createType4;
        const $$createField12_0 = $$createType3;
        const $$createField13_0 = $$createType1;
        const $$createField17_0 = $$createType6;
        const $$createField29_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("urls" in $$parsedSource) {
            $$parsedSource["urls"] = $$createField11_0($$parsedSource["urls"]);
        }
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField12_0($$parsedSource["tags"]);
        }
        if ("performers" in $$parsedSource) {
            $$parsedSource["performers"] = $$createField13_0($$parsedSource["performers"]);
        }
        if ("attachments" in $$parsedSource) {
            $$parsedSource["attachments"] = $$createField17_0($$parsedSource["attachments"]);
        }
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField29_0($$parsedSource["files"]);
        }
        return new SceneDetailDTO($$parsedSource as Partial<SceneDetailDTO>);
    }
}

/**
 * SceneFileDTO is a single video file of a scene.
 */
export class SceneFileDTO {
    "id": number;
    "path": string;
    "basename": string;
    "duration": number;
    "width": number;
    "height": number;
    "videoCodec": string;
    "audioCodec": string;
    "frameRate": number;
    "bitrate": number;
    "format": string;

    /** Creates a new SceneFileDTO instance. */
    constructor($$source: Partial<SceneFileDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("basename" in $$source)) {
            this["basename"] = "";
        }
        if (!("duration" in $$source)) {
            this["duration"] = 0;
        }
        if (!("width" in $$source)) {
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            this["height"] = 0;
        }
        if (!("videoCodec" in $$source)) {
            this["videoCodec"] = "";
        }
        if (!("audioCodec" in $$source)) {
            this["audioCodec"] = "";
        }
        if (!("frameRate" in $$source)) {
            this["frameRate"] = 0;
        }
        if (!("bitrate" in $$source)) {
            this["bitrate"] = 0;
        }
        if (!("format" in $$source)) {
            this["format"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SceneFileDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): SceneFileDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SceneFileDTO($$parsedSource as Partial<SceneFileDTO>);
    }
}

/**
 * ScenesFilter 是场景列表的过滤条件（nil 表示不过滤）。
 */
export class ScenesFilter {
    /**
     * nil=全部
     */
    "organized": boolean | null;

    /**
     * >= 阈值（0-100）
     */
    "ratingMin": number | null;

    /**
     * YYYY-MM-DD
     */
    "dateFrom": string;
    "dateTo": string;
    "tagIds": number[];

    /**
     * true=全部命中，默认任一
     */
    "tagAll": boolean;

    /**
     * 含子孙标签
     */
    "includeSubTags": boolean;
    "performerIds": number[];

    /**
     * 默认 true=全部命中
     */
    "performerAll": boolean;
    "studioId": number | null;
    "includeSubStudios": boolean;

    /** Creates a new ScenesFilter instance. */
    constructor($$source: Partial<ScenesFilter> = {}) {
        if (!("organized" in $$source)) {
            this["organized"] = null;
        }
        if (!("ratingMin" in $$source)) {
            this["ratingMin"] = null;
        }
        if (!("dateFrom" in $$source)) {
            this["dateFrom"] = "";
        }
        if (!("dateTo" in $$source)) {
            this["dateTo"] = "";
        }
        if (!("tagIds" in $$source)) {
            this["tagIds"] = [];
        }
        if (!("tagAll" in $$source)) {
            this["tagAll"] = false;
        }
        if (!("includeSubTags" in $$source)) {
            this["includeSubTags"] = false;
        }
        if (!("performerIds" in $$source)) {
            this["performerIds"] = [];
        }
        if (!("performerAll" in $$source)) {
            this["performerAll"] = false;
        }
        if (!("studioId" in $$source)) {
            this["studioId"] = null;
        }
        if (!("includeSubStudios" in $$source)) {
            this["includeSubStudios"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScenesFilter instance from a string or object.
     */
    static createFrom($$source: any = {}): ScenesFilter {
        const $$createField4_0 = $$createType9;
        const $$createField7_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tagIds" in $$parsedSource) {
            $$parsedSource["tagIds"] = $$createField4_0($$parsedSource["tagIds"]);
        }
        if ("performerIds" in $$parsedSource) {
            $$parsedSource["performerIds"] = $$createField7_0($$parsedSource["performerIds"]);
        }
        return new ScenesFilter($$parsedSource as Partial<ScenesFilter>);
    }
}

/**
 * ScenesPageDTO 是场景列表的分页结果。
 */
export class ScenesPageDTO {
    "scenes": SceneDTO[];
    "total": number;
    "page": number;
    "pageSize": number;

    /** Creates a new ScenesPageDTO instance. */
    constructor($$source: Partial<ScenesPageDTO> = {}) {
        if (!("scenes" in $$source)) {
            this["scenes"] = [];
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("page" in $$source)) {
            this["page"] = 0;
        }
        if (!("pageSize" in $$source)) {
            this["pageSize"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScenesPageDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): ScenesPageDTO {
        const $$createField0_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("scenes" in $$parsedSource) {
            $$parsedSource["scenes"] = $$createField0_0($$parsedSource["scenes"]);
        }
        return new ScenesPageDTO($$parsedSource as Partial<ScenesPageDTO>);
    }
}

/**
 * ScenesQuery 是场景列表的查询入参（过滤字段将在后续子步骤中追加，方法签名不变）。
 */
export class ScenesQuery {
    "query": string;
    "page": number;
    "pageSize": number;
    "filter"?: ScenesFilter | null;

    /** Creates a new ScenesQuery instance. */
    constructor($$source: Partial<ScenesQuery> = {}) {
        if (!("query" in $$source)) {
            this["query"] = "";
        }
        if (!("page" in $$source)) {
            this["page"] = 0;
        }
        if (!("pageSize" in $$source)) {
            this["pageSize"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScenesQuery instance from a string or object.
     */
    static createFrom($$source: any = {}): ScenesQuery {
        const $$createField3_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("filter" in $$parsedSource) {
            $$parsedSource["filter"] = $$createField3_0($$parsedSource["filter"]);
        }
        return new ScenesQuery($$parsedSource as Partial<ScenesQuery>);
    }
}

/**
 * StudioDTO 是工作室的列表项。
 */
export class StudioDTO {
    "id": number;
    "name": string;

    /** Creates a new StudioDTO instance. */
    constructor($$source: Partial<StudioDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StudioDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): StudioDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StudioDTO($$parsedSource as Partial<StudioDTO>);
    }
}

export class StudiosPageDTO {
    "studios": StudioDTO[];
    "total": number;
    "page": number;
    "pageSize": number;

    /** Creates a new StudiosPageDTO instance. */
    constructor($$source: Partial<StudiosPageDTO> = {}) {
        if (!("studios" in $$source)) {
            this["studios"] = [];
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("page" in $$source)) {
            this["page"] = 0;
        }
        if (!("pageSize" in $$source)) {
            this["pageSize"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StudiosPageDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): StudiosPageDTO {
        const $$createField0_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("studios" in $$parsedSource) {
            $$parsedSource["studios"] = $$createField0_0($$parsedSource["studios"]);
        }
        return new StudiosPageDTO($$parsedSource as Partial<StudiosPageDTO>);
    }
}

export class StudiosQuery {
    "query": string;
    "page": number;
    "pageSize": number;

    /** Creates a new StudiosQuery instance. */
    constructor($$source: Partial<StudiosQuery> = {}) {
        if (!("query" in $$source)) {
            this["query"] = "";
        }
        if (!("page" in $$source)) {
            this["page"] = 0;
        }
        if (!("pageSize" in $$source)) {
            this["pageSize"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StudiosQuery instance from a string or object.
     */
    static createFrom($$source: any = {}): StudiosQuery {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StudiosQuery($$parsedSource as Partial<StudiosQuery>);
    }
}

/**
 * TagDTO pairs a tag ID with its name so the frontend can look up either
 * without relying on parallel arrays.
 */
export class TagDTO {
    "id": number;
    "name": string;

    /** Creates a new TagDTO instance. */
    constructor($$source: Partial<TagDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TagDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): TagDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TagDTO($$parsedSource as Partial<TagDTO>);
    }
}

export class TagsPageDTO {
    "tags": TagDTO[];
    "total": number;
    "page": number;
    "pageSize": number;

    /** Creates a new TagsPageDTO instance. */
    constructor($$source: Partial<TagsPageDTO> = {}) {
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("page" in $$source)) {
            this["page"] = 0;
        }
        if (!("pageSize" in $$source)) {
            this["pageSize"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TagsPageDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): TagsPageDTO {
        const $$createField0_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField0_0($$parsedSource["tags"]);
        }
        return new TagsPageDTO($$parsedSource as Partial<TagsPageDTO>);
    }
}

export class TagsQuery {
    "query": string;
    "page": number;
    "pageSize": number;

    /** Creates a new TagsQuery instance. */
    constructor($$source: Partial<TagsQuery> = {}) {
        if (!("query" in $$source)) {
            this["query"] = "";
        }
        if (!("page" in $$source)) {
            this["page"] = 0;
        }
        if (!("pageSize" in $$source)) {
            this["pageSize"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TagsQuery instance from a string or object.
     */
    static createFrom($$source: any = {}): TagsQuery {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TagsQuery($$parsedSource as Partial<TagsQuery>);
    }
}

// Private type creation functions
const $$createType0 = PerformerDTO.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = TagDTO.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Array($Create.Any);
const $$createType5 = AttachmentDTO.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = SceneFileDTO.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = $Create.Array($Create.Any);
const $$createType10 = SceneDTO.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = ScenesFilter.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = StudioDTO.createFrom;
const $$createType15 = $Create.Array($$createType14);
